module.exports = [
  {
    recipe_name: 'Ultimate lemon meringue pie',
    ingredients: [
      { ingredient_name: 'flour', aisle: 'baking' },
      { ingredient_name: 'butter', aisle: 'fridge' },
      { ingredient_name: 'icing sugar', aisle: 'baking' },
      { ingredient_name: 'egg yolk', aisle: 'fridge' },
      { ingredient_name: 'cornflour', aisle: 'baking' },
      { ingredient_name: 'caster sugar', aisle: 'baking' },
      { ingredient_name: 'lemon', aisle: 'produce' },
      { ingredient_name: 'lemon juice', aisle: 'produce' },
      { ingredient_name: 'orange', aisle: 'produce' },
      { ingredient_name: 'egg', aisle: 'fridge' },
      { ingredient_name: 'egg whites', aisle: 'fridge' },
    ],
    steps: [
      'For the pastry, put 175g plain flour, 100g cold butter, cut into small pieces, 1 tbsp icing sugar, 1 egg yolk (save the white for the meringue) and 1 tbsp cold water into a food processor.',
      'Using the pulse button so the mix is not overworked, process until the mix starts to bind.',
      'Tip the pastry onto a lightly floured surface, gather together until smooth, then roll out and line a 23 x 2.5cm loose-bottom fluted flan tin.',
      'Trim and neaten the edges. Press pastry into flutes. The pastry is quite rich, so don’t worry if it cracks, just press it back together. Prick the base with a fork, line with foil, shiny side down, and chill for 1⁄2-1 hour (or overnight).',
      'Put a baking sheet in the oven and heat oven to 200C/fan 180C/gas 6. Bake the pastry case ‘blind’ (filled with dry beans) for 15 mins, then remove the foil and bake a further 5-8 mins until the pastry is pale golden and cooked.',
      'Set aside. Can be done a day ahead if you want to get ahead. Lower the oven to 180C/fan 160C/gas 4.',
      'While the pastry bakes, prepare the filling: mix 2 level tbsp cornflour, 100g golden caster sugar and finely grated zest of 2 large lemons in a medium saucepan. Strain and stir in 125ml lemon juice gradually.',
      'Make the juice of 1 small orange up to 200ml with water and strain into the pan. Cook over a medium heat, stirring constantly, until thickened and smooth. ',
      'Once the mixture bubbles, remove from the heat and beat in 85g butter until melted. Beat 3 egg yolks (save white for meringue) and 1 whole egg together, stir into the pan and return to a medium heat.',
      'Keep stirring vigorously for a few minutes, until the mixture thickens and plops from the spoon. (It will bubble, but doesn’t curdle.) Take off the heat and set aside while you make the meringue. ',
      'Put 4 egg whites in a large bowl. Whisk to soft peaks, then add 100g of the golden caster sugar a spoonful at a time, whisking between each addition without overbeating.',
      'Whisk in 2 level tsp cornflour, then add the remaining 100g of the golden caster sugar as before until smooth and thick. ',
      'Quickly reheat the filling and pour it into the pastry case. Immediately put spoonfuls of meringue around the edge of the filling (if you start in the middle the meringue may sink), then spread so it just touches the pastry (this will anchor it and help stop it sliding).',
      'Pile the rest into the centre, spreading so it touches the surface of the hot filling (and starts to cook), then give it all a swirl.',
      'Return to the oven for 18-20 mins until the meringue is crisp and slightly coloured. Let the pie sit in the tin for 30 mins, then remove and leave for at least another 1⁄2-1 hr before slicing. Eat the same day.',
    ],
  },

  {
    recipe_name: 'Glissade Chocolate Pudding',
    ingredients: [
      { ingredient_name: 'egg', aisle: 'fridge' },
      { ingredient_name: 'dark chocolate', aisle: 'candy' },
      { ingredient_name: 'water', aisle: 'water' },
      { ingredient_name: 'sugar', aisle: 'baking' },
      { ingredient_name: 'unsalted butter', aisle: 'fridge' },
      { ingredient_name: 'sea salt', aisle: 'baking' },
      { ingredient_name: 'heavy cream', aisle: 'fridge' },
    ],
    steps: [
      'Separate the whites and yolks of the eggs. In a large bowl, beat the egg whites until they hold very stiff peaks.',
      "Combine the chocolate, water, sugar, butter, and a pinch of salt in a double boiler. If you don't have a double-boiler, you can fashion one by combining the ingredients in a medium stainless steel bowl, and then placing this bowl atop a small simmering saucepan of water. The idea is to apply just enough gentle heat to melt the chocolate. Stir until the ingredients come together smoothly. Remove from heat, and beat in the egg yolks. Add the egg whites, and fold gently until the pudding is uniform in texture. Pour the pudding into serving cups or glasses, and chill well - preferably for a few hours. Serve topped with a bit of whipped cream.",
    ],
  },

  {
    recipe_name: 'Thai-spiced Pumpkin Soup Recipe',
    ingredients: [
      { ingredient_name: 'acorn squash', aisle: 'produce' },
      { ingredient_name: 'unsalted butter', aisle: 'fridge' },
      { ingredient_name: 'coconut milk', aisle: 'fridge' },
      { ingredient_name: 'red Thai curry paste', aisle: 'asian' },
      { ingredient_name: 'sea salt', aisle: 'baking' },
    ],
    steps: [
      'Preheat the oven to 375 degrees and place the oven racks in the middle.',
      'Carefully cut each squash/pumpkin into halves (or quarters). Slather each piece of squash with butter, sprinkle generously with salt, place on a baking sheet skin sides down, and place in the oven. Roast for about an hour or until the squash is tender throughout.',
      'When the pumpkin/squash are cool enough to handle scoop it into a large pot over medium high heat. Add the coconut milk and curry paste and bring to a simmer. Remove from the heat and puree with a hand blender, you should have a very thick base at this point. Now add water a cup at a time pureeing between additions until the soup is the consistency you prefer - a light vegetable stock would work here as well. Bring up to a simmer again and add the salt (and more curry paste if you like, I used just shy of 6 teaspoons but the curry paste I use is not over-the-top spicy).',
    ],
  },

  {
    recipe_name: 'Bread Pudding',
    ingredients: [
      { ingredient_name: 'French bread', aisle: 'bakery' },
      { ingredient_name: 'milk', aisle: 'fridge' },
      { ingredient_name: 'eggs', aisle: 'fridge' },
      { ingredient_name: 'sugar', aisle: 'baking' },
      { ingredient_name: 'vanilla extract', aisle: 'baking' },
      { ingredient_name: 'raisins', aisle: 'aisle 1' },
      { ingredient_name: 'allspice', aisle: 'baking' },
      { ingredient_name: 'cinnamon', aisle: 'baking' },
      { ingredient_name: 'unsalted butter', aisle: 'fridge' },
    ],
    steps: [
      'Preheat oven to 350°F.',
      'Soak bread in milk: Preheat oven to 350°F. Place milk in a large mixing bowl and add the bread that has been cut into squares. Press the bread into the milk with your hands until all of the milk is absorbed.',
      'Make egg mixture, pour over bread: In a separate bowl, whisk the eggs, then whisk in the sugar, vanilla, allspice and cinnamon. Pour over the bread and milk mixture. Add the bourbon soaked raisins and gently stir to combine.',
      'Butter baking pan, add bread mixture, bake: Pour the melted butter into the bottom of a 9x13 inch baking pan. Coat the bottom and the sides of the pan well with the butter. Pour the bread milk and egg mixture into the baking pan.',
      'Bake at 350°F for 35-45 minutes, until the liquid has set. The pudding is done when the edges start getting a bit brown and pull away from the edge of the pan. Can also make in individual ramekins.',
      'Make the bourbon sauce while the bread pudding is cooking. Melt the butter in a medium saucepan on low heat. Add the sugar and egg and whisk to blend well. Slowly cook over low heat, stirring constantly, until the mixture thickens enough to coat the back of a spoon, then remove from heat. Do not allow the mixture to simmer! (Or the sauce will curdle. By the way, if your sauce curdles, just take it off the heat and blend it smooth in a blender.)',
      'Whisk in bourbon to taste. Whisk again before serving. The sauce should be soft, creamy, and smooth.',
      'Serve the bread pudding with bourbon whiskey sauce on the side; pour on to taste. Best fresh and eaten the day it is made.',
    ],
  },

  {
    recipe_name: 'Cauliflower soup',
    ingredients: [
      { ingredient_name: 'cauliflower', aisle: 'produce' },
      { ingredient_name: 'carrot', aisle: 'produce' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'celery', aisle: 'produce' },
      { ingredient_name: 'chicken broth', aisle: 'soup' },
      { ingredient_name: 'milk', aisle: 'fridge' },
      { ingredient_name: 'half & half', aisle: 'fridge' },
      { ingredient_name: 'butter', aisle: 'fridge' },
      { ingredient_name: 'flour', aisle: 'baking' },
      { ingredient_name: 'salt', aisle: 'baking' },
      { ingredient_name: 'pepper', aisle: 'baking' },
      { ingredient_name: 'sour cream', aisle: 'fridge' },
      { ingredient_name: 'parsley', aisle: 'baking' },
    ],
    steps: [
      'Wash 1 to 2 heads of cauliflower, depending on how chunky you’d like the soup to be. I use about a head and 1/3 of another head.',
      'Just whack the head in half and get rid of the hard inner core and green parts.',
      'Then just roughly chop the cauliflower.',
      'Next, finely dice one carrot. I just cut strips in the carrot, then rotate the strips 90 degrees and finely dice.',
      'I do the same to the celery: just cut it into strips, then dice.',
      'Same goes with the onion: first cut lines/strips…',
      'Then dice away!',
      'Place a stock pot or dutch oven over medium high heat and melt 4 tablespoons butter in the pan. When the butter’s melted, throw in the onions.',
      'Stir them around for 2 to 3 minutes, or until they get a little color.',
      'Throw in the carrots and celer and stir for a minute or so.',
      'Now just throw in the cauliflower. If it’s finely diced, it should measure to about 2 quarts. If it’s large and weird like mine, more like 3 quarts.',
      'Next, and please don’t hate me, add 2 tablespoons fresh parsley, if you have it. PLEASE, IN THE NAME OF ALL THAT IS GOOD IN THE WORLD AND YOU FIND YOURSELF LUCKY ENOUGH TO LIVE NEAR A SUPERMARKET THAT CARRIES FRESH PARSLEY, add it in.',
      'Give it a good stir, reduce the heat to low…',
      'And cover the pot. Simmer on low heat for 15 minutes, stirring once or twice during the process.',
      'When 15 minutes is over, pour in 2 quarts of chicken broth. If you have homemade stock in your freezer, go for it. If you don’t, but it in the store. Just be sure to buy the low sodium variety so you’ll be able to control the salt content of the soup.',
      'Bring to a boil over medium heat, then reduce heat and let the soup simmer.',
      'While it’s simmering, melt 4 tablespoons butter in a medium saucepan over medium-low heat.',
      'In a separate bowl, pour 2 cups whole milk. I always use whole milk in soups because…well, because.',
      'Add 6 tablespons flour to the milk and mix together with a whisk',
      'As soon as the butter in melted pour the milk/flour mixture into the saucepan.',
      'Stir to combine. Almost immediately, it’ll thicken into a nice white sauce.',
      'Next, because the world is a crazy place, add 1 cup of half & half to the white sauce.',
      'And now for the fun part: Pour the white sauce into the simmering soup mixture.',
      'Now, just throw in a bay leaf or two.',
      'Now just let the soup simmer for 15 to 20 minutes. It’ll fill your house with fanciful aromas and feelings.',
      'Now, here’s the kicker: just before serving, throw 1 generous cup of sour cream into the serving bowl or tureen.',
    ],
  },

  {
    recipe_name: 'Super-Delicious Zuppa Toscana',
    ingredients: [
      { ingredient_name: 'mild Italian sausage', aisle: 'meat' },
      { ingredient_name: 'crushed red pepper', aisle: 'produce' },
      { ingredient_name: 'bacon', aisle: 'meat' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'minced garlic', aisle: 'produce' },
      { ingredient_name: 'chicken broth', aisle: 'soup' },
      { ingredient_name: 'potatoes', aisle: 'produce' },
      { ingredient_name: 'heavy cream', aisle: 'fridge' },
      { ingredient_name: 'fresh spinach', aisle: 'produce' },
    ],
    steps: [
      'Cook the Italian sausage and red pepper flakes in a Dutch oven over medium-high heat until crumbly, browned, and no longer pink, 10 to 15 minutes. Drain and set aside.',
      'Cook the bacon in the same Dutch oven over medium heat until crisp, about 10 minutes. Drain, leaving a few tablespoons of drippings with the bacon in the bottom of the Dutch oven. Stir in the onions and garlic; cook until onions are soft and translucent, about 5 minutes.',
      'Pour the chicken broth into the Dutch oven with the bacon and onion mixture; bring to a boil over high heat. Add the potatoes, and boil until fork tender, about 20 minutes. Reduce the heat to medium and stir in the heavy cream and the cooked sausage; heat through. Mix the spinach into the soup just before serving.',
    ],
  },

  {
    recipe_name: 'Sweet Potato Kale Pizza with Rosemary & Red Onion',
    ingredients: [
      { ingredient_name: 'pizza dough', aisle: 'bakery' },
      { ingredient_name: 'sweet potato', aisle: 'produce' },
      { ingredient_name: 'red onion', aisle: 'produce' },
      { ingredient_name: 'olive oil', aisle: 'oil' },
      { ingredient_name: 'salt', aisle: 'baking' },
      { ingredient_name: 'pepper', aisle: 'baking' },
      { ingredient_name: 'mozzarella cheese', aisle: 'dairy' },
      { ingredient_name: 'kale', aisle: 'produce' },
      { ingredient_name: 'balsamic vinegar', aisle: 'oil' },
      { ingredient_name: 'rosemary', aisle: 'seasoning' },
    ],
    steps: [
      'Preheat the oven to 400 degrees F. Place the sweet potato slices and red onion slices in a bowl and toss with 1/2 tablespoon of the olive oil. Season with salt and pepper. Place on a large baking sheet and bake for about 20 minutes, or until the sweet potatoes are soft and tender. Make sure you turn them once during the 20 minutes. Remove from oven and let cool while you prepare the pizza dough.',
      'Turn the oven to 500 degrees F or as high as your oven will go. If you have a pizza stone, place the pizza stone in the oven to get hot. On a lightly floured surface, roll out the pizza dough, using a rolling pin. Roll it out to about 3/8 of an inch. Place the pizza dough on a pizza peel or pan that has been generously coated with corn meal. Lightly brush the dough with the remaining 1 tablespoon of olive oil. In a small bowl, toss the kale with balsamic vinegar. Top the pizza dough with mozzarella cheese, sweet potato slices, kale, red onion slices, and fresh rosemary.',
      'Place the pizza in the oven-directly on the pizza stone, if using one, or on the oven rack. Bake for 10-15 minutes or until pizza crust is golden and cheese is melted. Remove from oven and let cool for a few minutes before slicing. Slice and serve warm.',
    ],
  },

  {
    recipe_name: 'African Chicken Peanut Stew',
    ingredients: [
      { ingredient_name: 'chicken legs', aisle: 'meat' },
      { ingredient_name: 'vegetable oil', aisle: 'oil' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'ginger', aisle: 'produce' },
      { ingredient_name: 'garlic cloves', aisle: 'produce' },
      { ingredient_name: 'sweet potatoes', aisle: 'produce' },
      { ingredient_name: 'chicken stock', aisle: 'soup' },
      { ingredient_name: 'peanut butter', aisle: 'snack' },
      { ingredient_name: 'roasted peanuts', aisle: 'snack' },
      { ingredient_name: 'ground coriander', aisle: 'seasoning' },
      { ingredient_name: 'cayenne', aisle: 'seasoning' },
      { ingredient_name: 'salt', aisle: 'seasoning' },
      { ingredient_name: 'black pepper', aisle: 'seasoning' },
      { ingredient_name: 'cilantro', aisle: 'produce' },
    ],
    steps: [
      "Heat the vegetable oil in a large soup pot set over medium-high heat. Salt the chicken pieces well, pat them dry and brown them in the oil. Don't crowd the pot, so do this in batches. Set the chicken pieces aside as they brown.",
      'Sauté the onions in the oil for 3-4 minutes, stirring often and scraping any browned bits off the bottom of the pot. Add the ginger and garlic and sauté another 1-2 minutes, then add the sweet potatoes and stir well to combine.',
      'Add the chicken, chicken broth, crushed tomatoes, peanut butter, peanuts, coriander and cayenne and stir well to combine. Bring to a simmer and taste for salt, adding more if needed.',
      'Cover the pot and simmer gently for 90 minutes (check after an hour), or until the chicken meat easily falls off the bone and the sweet potatoes are tender.',
      'Remove the chicken pieces and set them in a bowl to cool, until cool enough to touch. Remove and discard the skin if you want, or chop it and put it back into the pot.',
      'Adjust the seasonings for salt and cayenne, then add as much black pepper as you think you can stand—the stew should be peppery. Stir in the cilantro and serve by itself, or with simple steamed rice.',
    ],
  },

  {
    recipe_name: 'Roasted Pumpkin Seeds',
    ingredients: [
      { ingredient_name: 'pumpkin seeds', aisle: 'produce' },
      { ingredient_name: 'salt water', aisle: 'water' },
    ],
    steps: ['Boil seeds in salted water', 'Toast in the oven'],
  },

  {
    recipe_name: 'French Toast',
    ingredients: [
      { ingredient_name: 'egg', aisle: 'fridge' },
      { ingredient_name: 'milk', aisle: 'fridge' },
      { ingredient_name: 'cinnamon', aisle: 'seasoning' },
      { ingredient_name: 'bread', aisle: 'bakery' },
      { ingredient_name: 'butter', aisle: 'fridge' },
      { ingredient_name: 'maple syrup', aisle: 'sauce' },
      { ingredient_name: 'orange zest', aisle: 'produce' },
      { ingredient_name: 'berries', aisle: 'produce' },
    ],
    steps: [
      ' In a medium bowl, whisk together the eggs, milk, and cinnamon. Stir in the orange zest and/or Triple Sec if using. Whisk the mixture until well blended and pour into a shallow bowl, wide enough to place a slice of the bread you will be using.',
      'Place each slice of bread into the milk egg mixture, allowing the bread to soak in some of it.',
      'Melt some butter in a large skillet over medium high heat. Shake off the excess egg mixture from the bread, and place the bread slices onto the hot skillet. Fry the French toast until browned on one side, then flip and brown the other side.',
      'Serve hot with butter, maple syrup, and if available, fresh berries.',
    ],
  },
  {
    recipe_name: 'meow mix',
    ingredients: [
      { ingredient_name: 'chicken', aisle: 'meat' },
      { ingredient_name: 'carrots', aisle: 'produce' },
      { ingredient_name: 'peas', aisle: 'produce' },
      { ingredient_name: 'pie crust', aisle: 'produce' },
      { ingredient_name: 'gravy', aisle: 'produce' },
      { ingredient_name: 'bone-meal', aisle: 'pets' },
    ],
    steps: [
      'cook the chicken',
      'make the rest of the pot pie',
      'insert bone-meal',
    ],
  },
  {
    recipe_name: 'hamburger helper',
    ingredients: [
      { aisle: 'pastry', ingredient_name: 'hamburger' },
      { aisle: 'gravy', ingredient_name: 'cheese' },
      { aisle: 'gravy', ingredient_name: 'noodles' },
      { aisle: 'salt', ingredient_name: 'salt' },
    ],
    steps: [
      'open crockpot',
      'hamburger',
      'noodles',
      'yay! you did it. and cheese',
    ],
  },
  {
    recipe_name: 'mac & cheese',
    ingredients: [
      { ingredient_name: 'cheese', aisle: 'cheese' },
      { ingredient_name: 'noodles', aisle: 'pre-packaged' },
    ],
    steps: ['heat water', 'pour cheese into pot', 'pour noodles into pot'],
  },
  {
    recipe_name: 'pad thai',
    ingredients: [
      { aisle: 'pre-packaged', ingredient_name: 'noodles' },
      { aisle: 'nut', ingredient_name: 'peanuts' },
      { aisle: 'produce', ingredient_name: 'lime' },
      { aisle: 'meant', ingredient_name: 'chicken' },
    ],
    steps: [
      'open crockpot',
      'put ingrediens in',
      'wait for pad thai',
      'yay! you did it',
      'one more hooray for peanuts',
    ],
  },
  {
    recipe_name: 'pizza',
    ingredients: [
      { ingredient_name: 'dough', aisle: 'meat' },
      { ingredient_name: 'pepperoni', aisle: 'produce' },
      { ingredient_name: 'cheese', aisle: 'produce' },
    ],
    steps: [
      'flip the dough',
      'spread a the sauce',
      'helicopter ingredients',
      'meow meow meow meow',
    ],
  },
  {
    recipe_name: 'Kentucky fried chicken',
    ingredients: [
      { aisle: 'meat', ingredient_name: 'chicken' },
      { aisle: 'spices', ingredient_name: 'all spice' },
      { aisle: 'bread', ingredient_name: 'bread crumbs' },
      { aisle: 'salt', ingredient_name: 'salt' },
    ],
    steps: ['heat up oil', 'grease chicken', 'dump bread crumbs', 'fry'],
  },
  {
    recipe_name: 'scrambled eggs',
    ingredients: [{ ingredient_name: 'meat', aisle: 'eggs' }],
    steps: [
      'heat pan',
      'crack eggs',
      'stir eggs',
      'mash eggs',
      'stir eggs again',
      'serve',
    ],
  },
  {
    recipe_name: 'lasagna',
    ingredients: [
      { aisle: 'cheese', ingredient_name: 'ricotta' },
      { aisle: 'pre-packaged', ingredient_name: 'noodles' },
      { aisle: 'sauce', ingredient_name: 'tomato sauce' },
      { aisle: 'meat', ingredient_name: 'hamburger' },
    ],
    steps: [
      'put into pan',
      'cook in oven ',
      'wait.',
      'wait..',
      'wait...',
      'throw it away its burnt',
    ],
  },
  {
    recipe_name: 'cookies',
    ingredients: [
      { ingredient_name: 'flour', aisle: 'baking' },
      { ingredient_name: 'sugar', aisle: 'baking' },
      { ingredient_name: 'peas', aisle: 'produce' },
    ],
    steps: ['make the cookies'],
  },
  {
    recipe_name: 'tacos',
    ingredients: [
      { aisle: 'produce', ingredient_name: 'lime' },
      { aisle: 'meat', ingredient_name: 'chicken' },
      { aisle: 'bread', ingredient_name: 'tortillas' },
      { aisle: 'sauce', ingredient_name: 'salsa' },
    ],
    steps: [
      'hire authenic mexican chef',
      'give up on hiring authentic chef they are much too money',
      'make tacos on tuesday',
      'celebrate your ignominy as you trample and appropriate mexican culture',
    ],
  },
  {
    recipe_name: 'coconut curry chicken',
    ingredients: [
      { ingredient_name: 'chicken breasts', aisle: 'meat' },
      { ingredient_name: 'garlic', aisle: 'produce' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'tomato', aisle: 'produce' },
      { ingredient_name: 'coconut milk', aisle: 'canned goods' },
      { ingredient_name: 'tomato sauce', aisle: 'condiment' },
      { ingredient_name: 'curry powder', aisle: 'spices' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
      { ingredient_name: 'sugar', aisle: 'spices' },
      { ingredient_name: 'vegetable oil', aisle: 'spices' },
    ],
    steps: [
      'season the chicken chunks with salt and pepper',
      'mix curry powder and oil',
      'heat a large skillet over medium-high heat and add the curry oil mixture',
      'heat curry oil for 1 minute',
      'add garlic and onions and cook for 1 minute',
      'add chicken chunks and toss lightly to coat with the curry oil mixture',
      'reduce heat to medium, and cook for 7 to 10 minutes, or until chicken is no longer pink in center and juices run clear',
      'pour coconut milk, diced tomatoes, tomato sauce, and sugar into the pan, and stir to combine, stirring',
      'cover and simmer, stirring occasionally, approximately 30 to 40 minutes',
      'serve immediately, over rice',
    ],
  },
  {
    recipe_name: 'flour tortillas',
    ingredients: [
      { ingredient_name: 'all-purpose flour', aisle: 'spices' },
      { ingredient_name: 'baking powder', aisle: 'spices' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'vegetable oil', aisle: 'spices' },
      { ingredient_name: 'water', aisle: '' },
    ],
    steps: [
      'in the bowl of a stand mixer fitted with the dough hook, combine flour, salt, and baking powder',
      'mix briefly to combine',
      'with the mixer running at medium speed, add oil and water',
      'mix for 1-2 minutes, stopping at least once to scrape the sides of the bowl',
      'after the dough begins to come together into a ball, reduce mixer speed to low and continue mixing for 1-2 minutes, until dough is smooth',
      'transfer dough at this point from the mixing bowl to a well-floured work surface',
      'divide into 16 roughly equal portions',
      'roll each portion into a ball and flatten slightly with the palm of our hand',
      'cover flattened balls of dough with a clean dish towel',
      'allow to rest for at least 15 minutes and up to an hour',
      'when ready to cook, warm a large cast-iron or heavy-bottomed skillet over medium-high heat',
      'keeping the work surface and rolling pin lightly floured, roll each dough ball into a circle abotu 6" in diameter',
      'transfer tortillas one at a time into the hot skillet',
      'cook for about 1 minute, until small bubbles form on the top and brown spots form on the bottom surface',
      'flip and cook the other side for about 30 seconds',
      'remove from the pan and stack cooked tortillas loosely wrapped in a clean kitchen towel',
      'serve immediately or allow to cool for later use',
    ],
  },
  {
    recipe_name: 'chocolate covered strawberry cupcakes',
    ingredients: [
      { ingredient_name: 'strawberries', aisle: 'produce' },
      { ingredient_name: 'eggs', aisle: 'dairy' },
      { ingredient_name: 'all-purpose flour', aisle: 'spices' },
      { ingredient_name: 'baking soda', aisle: 'spices' },
      {
        ingredient_name: "Hershey's special dark cocoa powder",
        aisle: 'spices',
      },
      { ingredient_name: 'pink red gel icing color', aisle: 'spices' },
      { ingredient_name: 'powdered sugar', aisle: 'spices' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'shortening', aisle: 'spices' },
      { ingredient_name: 'sugar', aisle: 'spices' },
      { ingredient_name: 'vanilla', aisle: 'spices' },
      { ingredient_name: 'vegetable oil', aisle: 'spices' },
      { ingredient_name: 'dark chocolate melting wafers', aisle: 'spices' },
      { ingredient_name: 'white chocolate melting wafers', aisle: 'spices' },
      { ingredient_name: 'butter, salted', aisle: 'dairy' },
      { ingredient_name: 'milk', aisle: 'dairy' },
      { ingredient_name: 'water', aisle: '' },
    ],
    steps: [
      'to make the chocolate covered strawberries, place the dark chocolate melting wafers into a small bowl and melt according to package instructions',
      'dip each strawberry into the chocolate, shaking off the excess chocolate',
      'place chocolate covered strawberry on parchment paper to dry',
      'place the white chocolate melting wafers into a small bowl and melt according to package instructions',
      'adding a small amount at a time, add some pink or red gel icing color and stir to combine',
      'add some pink or red gel icing color and stir to combine until you have your desired shade of pink',
      'drizzle the pink chocolate over the chocolate covered strawberries and allow to dry',
      'refrigerate srawberries until ready to use',
      'to make the cupcakes, preheat oven to 300 deg F and prepare a cupcake pan with liners',
      'add the dry ingredients to a large bowl and whisk together and set aside',
      'combine the egg, milk, vegetable oil and vanilla in another medium sized bowl',
      'add the wet ingredients to the dry ingredients and mix until well combined',
      'add the water to the batter and mix until well combined',
      'fill the cupcake liners about half way and bake for 18-23 minutes, or until a toothpick comes out with a few moist crumbs',
      'remove the cupcakes from oven and allow to cool for 2 minutes, then remove to a cooling rack to finish cooling',
      'to make the frosting, add the chopped strawberries to a food processor and puree until smooth',
      'strain the strawberry puree through a fine mesh sleeve and set puree aside',
      'beat the butter and shortening together in a large mixer bowl until well combined and smooth',
      'add 2 tablespoons of strawberry puree and mix until well combined',
      'add the remaining powdered sugar and mix until smooth',
      'add the remaining strawberry puree as needed to get the right consistency of frosting and flavor',
      'add pink or red gel icing color until you have your desired shade of pink frosting',
      'pipe the frosting onto the cupcakes',
      'top each cupcake with a chocolate covered strawberry',
    ],
  },
  {
    recipe_name: 'brownie banana bread',
    ingredients: [
      {
        ingredient_name: 'Betty Crocker Milk Chocolate brownie mix',
        aisle: 'baking',
      },
      { ingredient_name: 'bananas', aisle: 'produce' },
      { ingredient_name: 'butter', aisle: 'dairy' },
      { ingredient_name: 'eggs', aisle: 'dairy' },
      { ingredient_name: 'heavy whipping cream', aisle: 'dairy' },
      { ingredient_name: 'mini chocolate chips', aisle: 'baking' },
    ],
    steps: [
      'preheat oven to 350 degrees F',
      'line an 8x5-inch loaf pan with parchment paper',
      'spray the bottom only with cooking spray',
      'put the brownie mix in a medium bowl',
      'stir in mashed bananas, butter, eggs, and whipping cream just until combined',
      'stir in 1 cup of the chocolate chips',
      'pour the batter into the prepared pan and spread evenly',
      'sprinkle the remaining chocolate chips on top',
      'bake 75 to 90 minutes or until a toothpick inserted into the center comes out clean',
      'cover the bread loosely with foil at about the 1 hour mark to avoid over-browning or burning on top',
      'cool 20 minutes, then remove the loaf from the pan to a cooling rack until completely cooled',
    ],
  },
  {
    recipe_name: 'brown sugar and garlic pork loin',
    ingredients: [
      { ingredient_name: 'pork loin', aisle: 'meat' },
      { ingredient_name: 'garlic', aisle: 'produce' },
      { ingredient_name: 'brown sugar', aisle: 'spices' },
      { ingredient_name: 'canola oil', aisle: 'spices' },
      { ingredient_name: 'carrots', aisle: 'produce' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
    ],
    steps: [
      'preheat oven to 375 degrees',
      'mix 1/4 cup canola oil, salt, and pepper with sliced carrots and potatoes',
      'mix 1 tablespoon canola oil, brown sugar, garlic and rub all over pork loin',
      'on 1 large cookie sheet, put down some foil and add the carrots and potatoes',
      'spread apart the vegetables to make an opening in the pan for the pork',
      'add the pork to the pan',
      'roast the pork and vegetables for 40-50 minutes, or until a meat thermometer registers at 150 degrees in the center of the roast',
      'remove the pork onto a plate or cutting board to let it rest and cover it with a piece of foil',
      'let the pork rest for 5-10 minutes, then remove the veggies from the oven once you are ready to serve the pork',
    ],
  },
  {
    recipe_name: 'chicken and dumplings',
    ingredients: [
      { ingredient_name: 'whole chicken', aisle: 'meat' },
      { ingredient_name: 'carrots', aisle: 'produce' },
      { ingredient_name: 'celery', aisle: 'produce' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'water', aisle: '' },
      { ingredient_name: 'all-purpose flour', aisle: 'spices' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'vegetable shortening', aisle: 'spices' },
      { ingredient_name: 'chicken bouillon cubes', aisle: 'spices' },
      { ingredient_name: 'butter', aisle: 'dairy' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
    ],
    steps: [
      'remove and discard giblets from chicken cavity',
      'put the chicken and veggies in a large stockpot and cover with water',
      'bring to a quick boil, then continue cooking chicken for one hour',
      'remove chicken to large bowl to cool',
      'strain broth to remove leftover veggies or other particles',
      'return broth to stockpot',
      'once chicken is cool, remove skin, then cut chicken into bite sized pieces',
      'add chicken pieces back into chicken broth',
      'heat chicken and broth to boiling',
      'add bouillon cubes, salt and pepper to taste',
      'while chicken is coming to a boil, make the dumplings',
      'in a large bowl, using a pastry blender or 2 knives, cut the shortening and salt into the cup of flour, until shortening is the size of small peas',
      'add 1/2 cup hot water and 1/2 cup, plus 2 tablespoons of flour to the mixture',
      'stir and work the mixture until a soft dough ball forms',
      'divide dough into 3 equal sized balls, then let the dough rest for 10 minutes',
      'generously flour a work surface and roll each dough ball out one at a time, sprinkling with flour to keep dough from sticking to work surface',
      'roll out to about the size of a large pie crust',
      'cut dough into strips about an inch wide using a pizza cutter or knife and repeat process fro remaining dough balls',
      'drop dumplings a couple at a time into hot boiling chicken/broth mixture until all have been added to pot',
      'add butter and continue cooking',
      'make a slurry by mixing 1/4 cup water with 2 large tablespoons of flour',
      'stir well to combine, then add to soup pot and stir well',
      'cook an additional 10 minutes on high fully cook dumplings',
      'taste test broth and add additional salt and pepper if desired',
    ],
  },
  {
    recipe_name: 'southern black-eyed peas',
    ingredients: [
      { ingredient_name: 'bacon', aisle: 'meat' },
      { ingredient_name: 'ham hock', aisle: 'meat' },
      { ingredient_name: 'black-eyed peas, dried', aisle: 'dried goods' },
      { ingredient_name: 'carrots', aisle: 'produce' },
      { ingredient_name: 'celery', aisle: 'produce' },
      { ingredient_name: 'garlic powder', aisle: 'spices' },
      { ingredient_name: 'onion', aisle: 'produce' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
      { ingredient_name: 'cayenne pepper', aisle: 'spices' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'water', aisle: '' },
    ],
    steps: [
      'put the peas in a large saucepan or dutch oven',
      'cover the peas with water to about 3 inches over the peas and bring to a boil',
      'reduce heat, then simmer for 15 minutes',
      'place ham hock, sliced onion, celery, carrots, bacon, pepper, and garlic in the slow cooker and add 3 cups of water',
      'cover and cook on high for 1 hour',
      'drain the peas and transfer to the slow cooker',
      'reduce heat to low, cover, and cook for 5 to 7 hours',
      'remove the ham hock from the pot',
      'remove the meat from the hock and shred or chop before adding meat back to the peas',
      'taste and add salt and pepper as needed',
    ],
  },
  {
    recipe_name: 'garlic parmesan macaroni and cheese',
    ingredients: [
      { ingredient_name: 'garlic', aisle: 'produce' },
      { ingredient_name: 'garlic powder', aisle: 'spices' },
      { ingredient_name: 'parsley', aisle: 'produce' },
      { ingredient_name: 'mustard, dry', aisle: 'spices' },
      { ingredient_name: 'cellentani pasta, dry', aisle: 'dried goods' },
      { ingredient_name: 'all-purpose flour', aisle: 'spices' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
      { ingredient_name: 'butter, unsalted', aisle: 'dairy' },
      { ingredient_name: 'heavy cream', aisle: 'dairy' },
      { ingredient_name: 'low fat milk', aisle: 'dairy' },
      { ingredient_name: 'mozzarella cheese', aisle: 'dairy' },
      { ingredient_name: 'parmesan cheese', aisle: 'dairy' },
    ],
    steps: [
      'boil pasta until al dente, then drain and set aside',
      'in a small saucepan, add milk and garlic cloves and simmer for a few minutes until garlic softens and flavor infuses into the milk, then set aside',
      'in a medium saucepan, add butter and bring saucepan to low heat until butter is melted',
      'add in flour and whisk until smooth roux forms',
      'remove and discard garlic cloves from milk and then add milk into roux',
      'add in heavy cream, parmesan cheese, mozzarella cheese, garlic powder and mustard',
      'bring saucepan to medium heat',
      'whisk and stir until cheese is completely melted and sauce is thick and smooth',
      'add cooked pasta to cheese sauce, stirring until pasta is evely coated',
      'garnish with parsley and fresh ground pepper if desired before serving',
    ],
  },
  {
    recipe_name: 'drunken noodles',
    ingredients: [
      { ingredient_name: 'basil', aisle: 'produce' },
      { ingredient_name: 'garlic', aisle: 'produce' },
      { ingredient_name: 'thai chili', aisle: 'produce' },
      { ingredient_name: 'tomato', aisle: 'produce' },
      { ingredient_name: 'egg', aisle: 'dairy' },
      { ingredient_name: 'fish sauce', aisle: 'condiment' },
      { ingredient_name: 'soy sauce', aisle: 'condiment' },
      { ingredient_name: 'rice stick noodles', aisle: 'dried goods' },
      { ingredient_name: 'shrimp', aisle: 'seafood' },
      { ingredient_name: 'canola oil', aisle: 'spices' },
      { ingredient_name: 'lime', aisle: 'produce' },
    ],
    steps: [
      'prepare rice noodles by following the instructions on the package and set aside',
      'in a wok or frying pan over medium high heat, heat the oil and fry garlic for 1 minute, or until golden',
      'add shrimp and toss for approximately 2-3 minutes, until almost cooked, then add egg and stir for a couple seconds until egg starts to set',
      'add chili, zest from lime, tomatoes, fish sauce, and soy sauce and stir for a minute or so until the tomato is cooked and sauce is bubbling',
      'add rice noodles and toss until noodles are hot, evenly coated and ingredients are mixed well',
      'turn off heat and add basil',
      'toss and serve immediately',
    ],
  },
  {
    recipe_name: 'rosemary and garlic roast beef',
    ingredients: [
      { ingredient_name: 'boneless rib eye roast', aisle: 'meat' },
      { ingredient_name: 'fresh rosemary', aisle: 'produce' },
      { ingredient_name: 'garlic', aisle: 'produce' },
      { ingredient_name: 'salt', aisle: 'spices' },
      { ingredient_name: 'black pepper', aisle: 'spices' },
      { ingredient_name: 'olive oil', aisle: 'spices' },
      { ingredient_name: 'butter', aisle: 'dairy' },
      { ingredient_name: 'mushrooms', aisle: 'produce' },
      { ingredient_name: 'butter', aisle: 'dairy' },
      { ingredient_name: 'beef stock', aisle: 'canned goods' },
    ],
    steps: [
      'chop garlic',
      'slice mushrooms to roughly the same size',
      'preheat oven to 350 degrees F',
      'tie the roast and season generously with salt and black pepper',
      'mix together rosemary and garlic',
      'add 2 tablespoons of olive oil to the rosemary-garlic mixture, stir to combine, and set aside',
      'in a cast-iron skillet, over medium heat, heat 2 tablespoons of olive oil and, once smoking hot, sear all sides of the meat',
      'remove skillet from heat and brush the rosemary-garlic mixture all oveer the roast',
      'bring the roast, in the cast-iron skillet, to the preheated oven and cook for about 1 to 1 1/2 hours or until meat thermometer reads 135 degrees F (medium-rare)',
      'let meat rest for at least 10 minutes before serving',
      'while the roast is resting, saute the mushrooms over medium heat with 2 tablespoons of butter until cooked through and no liquid is left in the pan',
      'season mushrooms with salt and black pepper to taste',
      'remove roast from the cast-iron skillet and bring the skillet to the stovetop',
      'add stock to cast-iron skillet and deglaze the pan, scraping all the bits from the bottom, and allow to simmer until thick',
      'add mushrooms to cast-iron skillet and stir in 2 tablespoons of butter',
      'continue stirring until the sauce is silky, then place roast into pan and spoon sauce over roast',
      'garnish serving platter with fresh rosemary if desired',
    ],
  },
];
